"""SNS / platform connection setup — scaffold auth profiles, never store secrets."""

from __future__ import annotations

import json
import os
from datetime import date, datetime, timezone
from pathlib import Path
from typing import Any

import yaml

from .registry import list_platforms, load_catalog, load_platform

SNS_PLATFORMS = ("facebook", "x", "instagram", "linkedin", "reddit")


def default_auth_dir() -> Path:
    root = os.environ.get("KAMPFF_AUTH_DIR")
    if root:
        return Path(root)
    data = os.environ.get("KAMPFF_DATA")
    if data:
        return Path(data) / "auth"
    return Path("kampff-data") / "auth"


def platforms_with_connection() -> list[str]:
    out: list[str] = []
    for pid in list_platforms():
        try:
            cfg = load_platform(pid)
        except Exception:
            continue
        if cfg.get("connection"):
            out.append(pid)
    # Prefer SNS first, then the rest alphabetically
    sns = [p for p in SNS_PLATFORMS if p in out]
    rest = sorted(p for p in out if p not in SNS_PLATFORMS)
    return sns + rest


def get_connection(platform_id: str) -> dict[str, Any]:
    cfg = load_platform(platform_id)
    conn = cfg.get("connection")
    if not conn:
        raise KeyError(f"Platform '{platform_id}' has no connection setup block")
    return {"platform": cfg, "connection": conn}


def resolve_mode(conn: dict[str, Any], mode_id: str | None) -> dict[str, Any]:
    modes = conn.get("modes") or []
    if not modes:
        raise ValueError("No connection modes defined")
    if not mode_id:
        mode_id = conn.get("preferred_mode") or modes[0]["id"]
    for m in modes:
        if m.get("id") == mode_id:
            return m
    known = ", ".join(m.get("id", "?") for m in modes)
    raise KeyError(f"Unknown mode '{mode_id}'. Known: {known}")


def _env_present(name: str) -> bool:
    v = os.environ.get(name)
    return bool(v and str(v).strip())


def check_env_map(env_map: dict[str, str] | None, alt_env: dict[str, list[str]] | None = None) -> list[dict[str, Any]]:
    """Return status rows for each logical key."""
    rows: list[dict[str, Any]] = []
    env_map = env_map or {}
    alt_env = alt_env or {}
    for logical, primary in env_map.items():
        alts = alt_env.get(logical, [])
        names = [primary] + list(alts)
        found = next((n for n in names if _env_present(n)), None)
        rows.append(
            {
                "key": logical,
                "env": primary,
                "alt": alts,
                "set": found is not None,
                "resolved_as": found,
            }
        )
    return rows


def profile_dir(auth_dir: Path, ref: str) -> Path:
    return auth_dir / ref


def profile_path(auth_dir: Path, ref: str) -> Path:
    return profile_dir(auth_dir, ref) / "profile.yaml"


def load_auth_index(auth_dir: Path) -> dict[str, Any]:
    path = auth_dir / "auth.json"
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}


def save_auth_index(auth_dir: Path, index: dict[str, Any]) -> None:
    auth_dir.mkdir(parents=True, exist_ok=True)
    path = auth_dir / "auth.json"
    path.write_text(json.dumps(index, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def write_profile(
    auth_dir: Path,
    *,
    ref: str,
    platform_id: str,
    mode: dict[str, Any],
    extra: dict[str, Any] | None = None,
) -> Path:
    auth_dir.mkdir(parents=True, exist_ok=True)
    pdir = profile_dir(auth_dir, ref)
    pdir.mkdir(parents=True, exist_ok=True)
    payload: dict[str, Any] = {
        "id": ref,
        "platform": platform_id,
        "mode": mode.get("id"),
        "label": mode.get("label"),
        "type": mode.get("auth_type", "none"),
        "transport": mode.get("transport"),
        "env": mode.get("env") or {},
        "alt_env": mode.get("alt_env") or {},
        "created_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "notes": [
            "Secrets live in environment variables or OS secret store only.",
            "Never commit this directory if you later add local secret files.",
            "targets.json references this profile via auth_ref only.",
        ],
    }
    if extra:
        payload.update(extra)
    path = profile_path(auth_dir, ref)
    path.write_text(
        "# Generated by kampff-collect connect setup — no secrets in this file\n"
        + yaml.safe_dump(payload, sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )

    index = load_auth_index(auth_dir)
    index[ref] = {
        "type": mode.get("auth_type", "none"),
        "platform": platform_id,
        "mode": mode.get("id"),
        "profile": str(Path(ref) / "profile.yaml"),
    }
    save_auth_index(auth_dir, index)

    # gitignore hint inside auth dir
    gi = auth_dir / ".gitignore"
    if not gi.exists():
        gi.write_text("# Kampff auth profiles — keep secrets out of git\n*\n!.gitignore\n", encoding="utf-8")
    return path


def setup_connection(
    platform_id: str,
    *,
    ref: str | None = None,
    mode_id: str | None = None,
    auth_dir: Path | None = None,
) -> dict[str, Any]:
    auth_dir = auth_dir or default_auth_dir()
    pack = get_connection(platform_id)
    conn = pack["connection"]
    mode = resolve_mode(conn, mode_id)
    ref = ref or f"{platform_id}_{mode['id']}"
    path = write_profile(auth_dir, ref=ref, platform_id=platform_id, mode=mode)
    env_rows = check_env_map(mode.get("env"), mode.get("alt_env"))
    return {
        "ref": ref,
        "platform": platform_id,
        "mode": mode.get("id"),
        "profile": str(path),
        "auth_dir": str(auth_dir),
        "steps": mode.get("steps") or [],
        "env": env_rows,
        "targets_snippet": conn.get("targets_snippet"),
        "lawful_note": conn.get("lawful_note"),
        "ready": all(r["set"] for r in env_rows) if env_rows else True,
    }


def status_connection(
    platform_id: str | None = None,
    *,
    auth_dir: Path | None = None,
) -> list[dict[str, Any]]:
    auth_dir = auth_dir or default_auth_dir()
    index = load_auth_index(auth_dir)
    rows: list[dict[str, Any]] = []

    def one(pid: str) -> None:
        try:
            pack = get_connection(pid)
        except KeyError:
            return
        conn = pack["connection"]
        pref = resolve_mode(conn, conn.get("preferred_mode"))
        # Profiles pointing at this platform
        refs = [r for r, meta in index.items() if meta.get("platform") == pid]
        env_rows = check_env_map(pref.get("env"), pref.get("alt_env"))
        # If a profile exists, prefer its env map
        if refs:
            pref_path = profile_path(auth_dir, refs[0])
            if pref_path.exists():
                data = yaml.safe_load(pref_path.read_text(encoding="utf-8")) or {}
                env_rows = check_env_map(data.get("env") or {}, data.get("alt_env") or {})
        export_ok = True
        for r in env_rows:
            if r["key"] in ("export_dir",) and r["set"]:
                p = Path(os.environ[r["resolved_as"]])
                export_ok = p.exists()
                r["path_exists"] = export_ok
        ready = (all(r["set"] for r in env_rows) if env_rows else True) and export_ok
        if any(r.get("key") == "password" for r in env_rows):
            # password may be set; don't echo
            pass
        rows.append(
            {
                "platform": pid,
                "preferred_mode": pref.get("id"),
                "profiles": refs,
                "env": env_rows,
                "ready": ready and bool(refs),
                "scaffold_only": bool(refs) and not ready,
                "missing_profile": not refs,
            }
        )

    if platform_id:
        one(platform_id)
    else:
        for pid in platforms_with_connection():
            if pid in SNS_PLATFORMS or platform_id is None:
                one(pid)
        # de-dupe if we iterated all
    # When no filter, only show SNS by default for connect status
    if platform_id is None:
        rows = [r for r in rows if r["platform"] in SNS_PLATFORMS]
        # ensure all SNS appear even without connection load issues
        seen = {r["platform"] for r in rows}
        for pid in SNS_PLATFORMS:
            if pid not in seen:
                try:
                    one(pid)
                except Exception as e:
                    rows.append({"platform": pid, "error": str(e), "ready": False})
        # rebuild unique
        by_p = {r["platform"]: r for r in rows}
        rows = [by_p[p] for p in SNS_PLATFORMS if p in by_p]
    return rows


def format_setup_report(result: dict[str, Any]) -> str:
    lines = [
        f"Connection scaffolded: {result['platform']} / mode={result['mode']}",
        f"  auth_ref : {result['ref']}",
        f"  profile  : {result['profile']}",
        f"  auth_dir : {result['auth_dir']}",
        "",
        "Setup steps:",
    ]
    for i, step in enumerate(result.get("steps") or [], 1):
        lines.append(f"  {i}. {step}")
    lines.append("")
    lines.append("Environment checklist:")
    for row in result.get("env") or []:
        mark = "OK " if row["set"] else "MISSING"
        alt = f" (alt: {', '.join(row['alt'])})" if row.get("alt") else ""
        lines.append(f"  [{mark}] {row['env']}{alt}")
    if result.get("lawful_note"):
        lines.append("")
        lines.append(f"Lawful use: {result['lawful_note'].strip()}")
    snip = result.get("targets_snippet")
    if snip:
        snip = dict(snip)
        snip["auth_ref"] = result["ref"]
        lines.append("")
        lines.append("targets.json snippet:")
        lines.append(json.dumps(snip, ensure_ascii=False, indent=2))
    lines.append("")
    if result.get("ready"):
        lines.append("Status: READY (required env present)")
    else:
        lines.append("Status: SCAFFOLDED — set missing env, then: kampff-collect connect status")
    return "\n".join(lines)


def format_status_report(rows: list[dict[str, Any]]) -> str:
    if not rows:
        return "No SNS connection platforms found."
    lines = ["Kampff SNS connection status", ""]
    for r in rows:
        if r.get("error"):
            lines.append(f"{r['platform']:12} ERROR {r['error']}")
            continue
        if r.get("ready"):
            state = "READY"
        elif r.get("scaffold_only"):
            state = "ENV_MISSING"
        elif r.get("missing_profile"):
            state = "NOT_SETUP"
        else:
            state = "UNKNOWN"
        refs = ",".join(r.get("profiles") or []) or "-"
        lines.append(f"{r['platform']:12} {state:12} mode={r.get('preferred_mode')}  refs={refs}")
        for er in r.get("env") or []:
            mark = "ok" if er["set"] else "--"
            extra = ""
            if "path_exists" in er:
                extra = " path_ok" if er["path_exists"] else " path_MISSING"
            lines.append(f"             [{mark}] {er['env']}{extra}")
    lines.append("")
    lines.append("Setup: kampff-collect connect setup --platform <facebook|x|instagram|linkedin|reddit>")
    lines.append("Guide: docs/sns-connection-setup.md")
    return "\n".join(lines)


def list_sns_catalog() -> list[dict[str, Any]]:
    out = []
    for pid in SNS_PLATFORMS:
        try:
            cfg = load_platform(pid)
            conn = cfg.get("connection") or {}
            modes = [m.get("id") for m in conn.get("modes") or []]
            out.append(
                {
                    "id": pid,
                    "label": cfg.get("label"),
                    "transport": cfg.get("transport"),
                    "auth": cfg.get("auth"),
                    "preferred_mode": conn.get("preferred_mode"),
                    "modes": modes,
                }
            )
        except KeyError:
            out.append({"id": pid, "error": "platform yaml missing"})
    return out


def print_sns_list() -> str:
    lines = ["SNS platforms with connection setup:", ""]
    for e in list_sns_catalog():
        if e.get("error"):
            lines.append(f"  {e['id']:12} MISSING — {e['error']}")
            continue
        modes = ", ".join(e.get("modes") or [])
        lines.append(
            f"  {e['id']:12} {e.get('label', '')}\n"
            f"               transport={e.get('transport')} auth={e.get('auth')} "
            f"preferred={e.get('preferred_mode')} modes=[{modes}]"
        )
    lines.append("")
    lines.append("kampff-collect connect setup --platform x --ref x_api")
    return "\n".join(lines)


def sample_targets_sns(batch_date: str | None = None) -> dict[str, Any]:
    """Synthetic multi-SNS targets skeleton (no secrets)."""
    d = batch_date or date.today().isoformat()
    return {
        "batch_date": d,
        "viewer_id": "me",
        "context": "sns",
        "protocol": "spectrograph",
        "analysis_lenses": ["personal", "mbti", "cia_sat"],
        "people": [
            {"id": "me", "display_name": "viewer", "aliases": []},
            {
                "id": "target_id",
                "display_name": "",
                "aliases": ["@their_x", "u/their_reddit", "their_ig"],
            },
        ],
        "targets": [
            {
                "url": "https://x.com/their_x",
                "platform": "x",
                "scope": "profile_by_username:their_x",
                "collect": ["post", "reply"],
                "match_people": ["target_id"],
                "auth_ref": "x_api",
                "query": {"username": "their_x", "limit": 100},
            },
            {
                "url": "https://www.reddit.com/user/their_reddit/",
                "platform": "reddit",
                "scope": "user:their_reddit",
                "collect": ["post", "comment"],
                "match_people": ["target_id"],
                "auth_ref": "reddit_oauth",
                "query": {"username": "their_reddit", "limit": 100},
            },
            {
                "url": "https://www.facebook.com/example_page/",
                "platform": "facebook",
                "scope": "page:PAGE_ID",
                "collect": ["post", "comment"],
                "match_people": ["target_id"],
                "auth_ref": "facebook_graph",
                "query": {"page_id": "PAGE_ID", "limit": 50},
            },
            {
                "url": "https://www.instagram.com/their_ig/",
                "platform": "instagram",
                "scope": "business:IG_USER_ID",
                "collect": ["post", "comment"],
                "match_people": ["target_id"],
                "auth_ref": "instagram_graph",
                "query": {"ig_user_id": "IG_USER_ID", "handle": "their_ig", "limit": 50},
            },
            {
                "url": "file://linkedin-export",
                "platform": "linkedin",
                "scope": "export_package",
                "collect": ["post", "comment"],
                "match_people": ["me"],
                "auth_ref": "linkedin_export",
                "query": {"path": "${LINKEDIN_EXPORT_DIR}"},
            },
        ],
        "meta": {
            "language": "ko",
            "timezone": "Asia/Seoul",
            "notes": "Fill auth via kampff-collect connect setup. Lawful API/export only.",
        },
    }
